--- === THỐNG KÊ SỐ LƯỢNG BẢN GHI IDB ===
SELECT 'VANPHONGDAIDIEN' AS TenBang, COUNT(*) AS SoBanGhi FROM VANPHONGDAIDIEN
UNION ALL
SELECT 'CUAHANG', COUNT(*) FROM CUAHANG
UNION ALL
SELECT 'KHACHHANG', COUNT(*) FROM KHACHHANG
UNION ALL
SELECT 'KHACHHANGDULICH', COUNT(*) FROM KHACHHANGDULICH
UNION ALL
SELECT 'KHACHHANGHBUUDIEN', COUNT(*) FROM KHACHHANGBUUDIEN
UNION ALL
SELECT 'MATHANG', COUNT(*) FROM MATHANG
UNION ALL
SELECT 'MATHANGLUUTRU', COUNT(*) FROM MATHANGLUUTRU
UNION ALL
SELECT 'DONDATHANG', COUNT(*) FROM DONDATHANG
UNION ALL
SELECT 'MATHANGDUOCDAT', COUNT(*) FROM MATHANGDUOCDAT
ORDER BY TenBang;

-- Thống kê số bản ghi theo bảng DW
SELECT 'Dim_ThoiGian' AS TenBang,COUNT(*) AS SoBanGhi,'Chiều thời gian (YYYYMM)' AS MoTa
FROM Dim_ThoiGian
UNION ALL
SELECT 'Dim_KhachHang',COUNT(*),'Chiều khách hàng (hợp nhất 3 nguồn)'
FROM Dim_KhachHang
UNION ALL
SELECT 'Dim_CuaHang',COUNT(*),'Chiều cửa hàng (gộp VPĐD)'
FROM Dim_CuaHang
UNION ALL
SELECT 'Dim_MatHang',COUNT(*),'Chiều sản phẩm (có NhomSP)'
FROM Dim_MatHang
UNION ALL
SELECT 'FACT_DOANH_SO',COUNT(*),'Fact doanh thu (Grain: KH×MH×Tháng)'
FROM FACT_DOANH_SO
UNION ALL
SELECT 'FACT_TON_KHO',COUNT(*),'Fact tồn kho cuối kỳ (Grain: CH×MH×Tháng)'
FROM FACT_TON_KHO
ORDER BY TenBang;

-- Xem dữ liệu ở các bảng Dim và Fact
SELECT * FROM Dim_KhachHang;
SELECT * FROM Dim_ThoiGian;
SELECT * FROM Dim_CuaHang;
SELECT * FROM Dim_MatHang;
SELECT * FROM Fact_Doanh_So;
SELECT * FROM Fact_Ton_Kho;

-- Sinh dữ liệu cho bảng Dim
SET SERVEROUTPUT ON;
DECLARE
  V_START_KH INT;
BEGIN
  SELECT NVL(MAX(KHACHHANG_KEY), 0) INTO V_START_KH FROM DIM_KHACHHANG;
  
  INSERT INTO DIM_KHACHHANG (
    KHACHHANG_KEY, MAKH_NGUON, TENKH, LOAIKH, HUONGDANVIEN, DIACHIBUUDIEN, TENTP_SONG, BANG_SONG
  )
  SELECT
    V_START_KH + LEVEL,
    'KH_' || LPAD(LEVEL, 4, '0'),
    'NGUYEN_VAN_' || DBMS_RANDOM.STRING('U', 3) || '_' || LEVEL,
    CASE MOD(LEVEL, 10)
      WHEN 0 THEN 'CaHai' WHEN 1 THEN 'CaHai' WHEN 2 THEN 'CaHai'
      WHEN 3 THEN 'CaHai' WHEN 4 THEN 'CaHai' WHEN 5 THEN 'CaHai'
      WHEN 6 THEN 'DuLich' WHEN 7 THEN 'DuLich' WHEN 8 THEN 'DuLich'
      ELSE 'BuuDien'
    END,
    CASE WHEN MOD(LEVEL, 3) != 0 THEN 'HDV_' || LPAD(TRUNC(DBMS_RANDOM.VALUE(1,50)),2,'0') ELSE NULL END,
    CASE WHEN MOD(LEVEL, 3) != 1 THEN 'SO_' || TRUNC(DBMS_RANDOM.VALUE(1,99)) || '_PHO_' || DBMS_RANDOM.STRING('U',4) ELSE NULL END,
    CASE MOD(LEVEL, 8)
      WHEN 0 THEN 'Ha Noi' WHEN 1 THEN 'TP.HCM' WHEN 2 THEN 'Da Nang'
      WHEN 3 THEN 'Hai Phong' WHEN 4 THEN 'Can Tho' WHEN 5 THEN 'Nghe An'
      WHEN 6 THEN 'Khanh Hoa' ELSE 'Lam Dong'
    END,
    CASE MOD(LEVEL, 8)
      WHEN 0 THEN 'HaNoi_Bang' WHEN 1 THEN 'HCM_Bang' WHEN 2 THEN 'DaNang_Bang'
      WHEN 3 THEN 'HaiPhong_Bang' WHEN 4 THEN 'CanTho_Bang' WHEN 5 THEN 'NgheAn_Bang'
      WHEN 6 THEN 'KhanhHoa_Bang' ELSE 'LamDong_Bang'
    END
  FROM DUAL CONNECT BY LEVEL <= 1000;
  
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('✅ Đã thêm 1.000 bản ghi vào DIM_KHACHHANG');
END;

-- Sinh dữ liệu cho bảng Dim_CuaHang
DECLARE
  V_START_CH INT;
BEGIN
  SELECT NVL(MAX(CUAHANG_KEY), 0) INTO V_START_CH FROM DIM_CUAHANG;
  
  INSERT INTO DIM_CUAHANG (
    CUAHANG_KEY, MACH_NGUON, TENCH, SODIENTHOAI, TENTP, BANG, DIACHIVP
  )
  SELECT
    V_START_CH + LEVEL,
    'CH_' || LPAD(LEVEL, 3, '0'),
    'CUAHANG_' || DBMS_RANDOM.STRING('U', 4) || '_' || LEVEL,
    '09' || TRUNC(DBMS_RANDOM.VALUE(10000000, 99999999)),
    CASE MOD(LEVEL, 5)
      WHEN 0 THEN 'Ha Noi' WHEN 1 THEN 'TP.HCM' WHEN 2 THEN 'Da Nang'
      WHEN 3 THEN 'Hai Phong' ELSE 'Can Tho'
    END,
    CASE MOD(LEVEL, 5)
      WHEN 0 THEN 'HaNoi_Bang' WHEN 1 THEN 'HCM_Bang' WHEN 2 THEN 'DaNang_Bang'
      WHEN 3 THEN 'HaiPhong_Bang' ELSE 'CanTho_Bang'
    END,
    'SO_' || TRUNC(DBMS_RANDOM.VALUE(1,200)) || '_DUONG_' || DBMS_RANDOM.STRING('U',5)
  FROM DUAL CONNECT BY LEVEL <= 100;
  
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('✅ Đã thêm 100 bản ghi vào DIM_CUAHANG');
END;

-- Sinh dữ liệu cho Dim_MatHang
DECLARE
  V_START_MH INT;
BEGIN
  SELECT NVL(MAX(MATHANG_KEY), 0) INTO V_START_MH FROM DIM_MATHANG;
  
  INSERT INTO DIM_MATHANG (
    MATHANG_KEY, MAMH_NGUON, NHOMSP, MOTA, KICHCO, TRONGLUONG, DONGIAHIENTAI
  )
  SELECT
    V_START_MH + LEVEL,
    'MH_' || LPAD(LEVEL, 4, '0'),
    CASE MOD(LEVEL, 4)
      WHEN 0 THEN 'Dien Tu' WHEN 1 THEN 'Van Phong'
      WHEN 2 THEN 'Thoi Trang' ELSE 'Gia Dung'
    END,
    'SANPHAM_' || DBMS_RANDOM.STRING('U', 5) || '_' || LEVEL,
    TRUNC(DBMS_RANDOM.VALUE(10,500)) || 'x' || TRUNC(DBMS_RANDOM.VALUE(10,300)) || 'mm',
    ROUND(DBMS_RANDOM.VALUE(0.1, 25.0), 2),
    ROUND(DBMS_RANDOM.VALUE(50000, 15000000), -2)
  FROM DUAL CONNECT BY LEVEL <= 300;
  
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('✅ Đã thêm 300 bản ghi vào DIM_MATHANG');
END;

